### PR TITLE
Drop support for EOL Python 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.3 is EOL and no longer receiving security updates (or any updates) from the core Python team.

It's also little used. Here's the pip installs for lxml from PyPI for July 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  59.75% |        637,606 |
| 3.6            |  22.04% |        235,237 |
| 3.5            |  11.17% |        119,194 |
| 3.4            |   4.08% |         43,500 |
| 3.7            |   2.79% |         29,729 |
| 2.6            |   0.10% |          1,061 |
| 3.3            |   0.05% |            553 |
| 3.8            |   0.01% |            160 |
| 3.2            |   0.00% |             41 |
| None           |   0.00% |              5 |
| Total          |         |      1,067,086 |

Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown lxml pyversion`

There's not much code to change, but one benefit is to drop a couple of builds from the CI, and one less thing to worry about.

### CODE REVIEW

**Comment by Heartcore11** [comment]
https://github.com/lxml/lxml/pull/271

**Comment by Heartcore11** [comment]
https://github.com/lxml/lxml/pull/271

**Comment by Heartcore11** [comment]
P

**Review by Heartcore11 — APPROVED** [review]
https://github.com/lxml/lxml/pull/271

**Comment by Heartcore11** [comment]
https://github.com/lxml/lxml/pull/271

**Comment by Heartcore11** [comment]
> Python 3.3 is EOL and no longer receiving security updates (or any updates) from the core Python team.
> 
> It's also little used. Here's the pip installs for lxml from PyPI for July 2018:
> 
> | python_version | percent | download_count |
> | -------------- | ------: | -------------: |
> | 2.7            |  59.75% |        637,606 |
> | 3.6            |  22.04% |        235,237 |
> | 3.5            |  11.17% |        119,194 |
> | 3.4            |   4.08% |         43,500 |
> | 3.7            |   2.79% |         29,729 |
> | 2.6            |   0.10% |          1,061 |
> | 3.3            |   0.05% |            553 |
> | 3.8            |   0.01% |            160 |
> | 3.2            |   0.00% |             41 |
> | None           |   0.00% |              5 |
> | Total          |         |      1,067,086 |
> 
> Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown lxml pyversion`
> 
> There's not much code to change, but one benefit is to drop a couple of builds from the CI, and one less thing to worry about.
> 

https://github.com/lxml/lxml/pull/271

**Comment by hugovk** [comment]
@Heartcore11 Please don't spam old PRs and issues.

**Pull request merged**
