### PR TITLE
Disable resolve_entities by default w/ one billion laughs expansion bug.

### PR DESCRIPTION
**Pull request by rogerhu**
Facebook recently issued its largest bug bounty to remove this security bug.

https://www.facebook.com/BugBounty/posts/778897822124446?stream_ref=10

This may result in breaking changes but should be considered an important
security enhancement.

Test fix included.

### CODE REVIEW

**Comment by plq** [comment]
Facebook's main fault here is not using Spyne. I would have protected them :D

Jokes aside, Spyne has always had numerous parser flags off due to similar security concerns. See https://github.com/arskom/spyne/blob/89b14bf00014be82933b8d7ce80af0919e6075e4/spyne/protocol/xml.py#L145 and also https://pypi.python.org/pypi/defusedxml for a good overview

https://github.com/arskom/spyne/blob/master/spyne/protocol/xml.py#L145

**Comment by boxed** [comment]
Ping?

Having your package insecure by default and pointing to the documentation is not a good approach. You should point to the documentation for how to ENABLE insecure features.

**Review by sabriabri88 — APPROVED** [review]

**Review by sabriabri88 — APPROVED** [review]

**Review by sabriabri88 — APPROVED** [review]

**Review by sabriabri88 — APPROVED** [review]

**Review by sabriabri88 — APPROVED** [review]

**Review by sabriabri88 — APPROVED** [review]

**Comment by clayg** [comment]
@boxed gets it - keep fighting brother!  :muscle:

**Comment by scoder** [comment]
See my comments above, specifically:

> My proposal would be to add a new parser option "resolve_file_entities". If that is False, which would be the new (backwards incompatible) default, then lxml would hook into the getEntity() callback function of the SAX parser (which points to xmlSAX2GetEntity() by default AFAICT) and reject any request for parsing an external entity.

and then, after thinking this through a bit more:

> We could change the existing boolean option "resolve_entities" into one that accepts string values. A non-empty string is True, so passing something like "internal" would result in a True value in old lxml versions and be correctly interpreted in new versions. Then we could change the default from True to "internal", which would disable external file loading. Users could then fix their code by passing True instead, if they really need that feature. That would reduce the number of affected users to a minimum, while still changing the default to something safer.

**Comment by scoder** [comment]
Superseded by https://github.com/lxml/lxml/pull/391

**Pull request closed without merging**
