### PR TITLE
Soup hyphen in comment

### PR DESCRIPTION
**Pull request by mozbugbox**
Fix a couple of issues with soupparser

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. Could you come up with a test that shows why the "--" special handling is necessary? At first glance, it seems wrong to me to *add* a character escape in text content (which is not serialised XML).

**Comment by mozbugbox** [comment]
Something like
```html
<html>
<body>
<div> Test </div>
<!-- This is -- a comment with double hyphen -->
</body>
</html>

```

When parsing with soupparser, exception raised 
```
 raise ValueError("Comment may not contain '--' or end with '-'")
```
The lxml code that raise the exception is in `lxml.etree.pyx`, `Comment()`.

**Comment by mozbugbox** [comment]
hmm... It seems lxml.html can parse comment with 2 hyphens with no problem.
```python
from lxml.html import soupparser
from lxml import html

content = "<html><!-- something with -- 2 hyphen --></html>"

tree = html.fromstring(content)
print(html.tostring(tree))

tree = soupparser.fromstring(content)
print(html.tostring(tree))
```

**Comment by scoder** [comment]
I think the soup parser is simply using the wrong way to instantiate an HTML comment:
```
>>> lxml.html.HtmlComment("something with -- 2 hyphen")
<!--something with -- 2 hyphen-->
```

**Comment by mozbugbox** [comment]
aha, thanks for the advice. Pull updated

**Comment by scoder** [comment]
Could you please also add tests to `test_elementsoup.py` ?

**Pull request merged**
