### PR TITLE
fixed namespace typo

### PR DESCRIPTION
**Pull request by udos**
fixed a minor typo in the docs

### CODE REVIEW

**Comment by scoder** [comment]
I can't see the advantage of using 't' instead of 'a' here.

**Comment by scoder** [comment]
but ok, I can live with 'a', too :)

**Comment by udos** [comment]
:) good. the example in the docs required the 'a'. with the 't' it would not work ;) I should have included the link -> http://lxml.de/xpathxslt.html#namespaces-and-prefixes

with this it becomes clearer, agreed?

**Comment by scoder** [comment]
Ah - now I remember why there was a 't' in there. 'a' would make it look like there was a correlation between the prefixes used in the input data and the those used in the XPath expression. It's better to keep different prefixes here, see the paragraph below the example.

**Comment by udos** [comment]
uff... I understand. sorry about this!

**Pull request merged**
