### PR TITLE
Add cython-lint to the testing

### PR DESCRIPTION
**Pull request by cclauss**
https://pypi.org/project/cython-lint

% `cython-lint --help`
```
usage: cython-lint [-h] [--max-line-length MAX_LINE_LENGTH] [--no-pycodestyle]
                   [paths ...]

positional arguments:
  paths

options:
  -h, --help            show this help message and exit
  --max-line-length MAX_LINE_LENGTH
  --no-pycodestyle
```

### CODE REVIEW

**Comment by cclauss** [comment]
% `shopt -s globstar && cython-lint **/*.pyx`
```
src/lxml/etree.pyx:50:34: 'config' imported but unused
src/lxml/etree.pyx:54:28: 'xpath' imported but unused
src/lxml/etree.pyx:55:28: 'c14n' imported but unused
src/lxml/etree.pyx:60:19: 'limits' imported but unused
src/lxml/etree.pyx:60:34: 'stdlib' imported but unused
src/lxml/etree.pyx:61:19: 'cstring_h' imported but unused
src/lxml/etree.pyx:62:26: 'const_char' imported but unused
src/lxml/etree.pyx:65:21: 'os_path_abspath' imported but unused
src/lxml/etree.pyx:68:25: 'StringIO' imported but unused
src/lxml/etree.pyx:71:25: 'OrderedDict' imported but unused
src/lxml/etree.pyx:83:23: 'partial' imported but unused
src/lxml/etree.pyx:86:23: 'islice' imported but unused
src/lxml/etree.pyx:96:1:  E302 expected 2 blank lines, found 1
src/lxml/etree.pyx:98:23:  W602 deprecated form of raising exception
src/lxml/etree.pyx:101:23:  W602 deprecated form of raising exception
src/lxml/etree.pyx:104:23:  W602 deprecated form of raising exception
src/lxml/etree.pyx:116:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/etree.pyx:155:89:  E501 line too long (116 > 88 characters)
src/lxml/etree.pyx:181:5: '_DEFAULT_NAMESPACE_PREFIXES_ITEMS' defined but unused
src/lxml/etree.pyx:188:53:  W605 invalid escape sequence '\d'
src/lxml/etree.pyx:190:1:  E302 expected 2 blank lines, found 1
src/lxml/etree.pyx:202:89:  E501 line too long (92 > 88 characters)
src/lxml/etree.pyx:235:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/etree.pyx:242:5:  E741 ambiguous variable name 'l'
src/lxml/etree.pyx:266:27:  E221 multiple spaces before operator
src/lxml/etree.pyx:267:19:  E221 multiple spaces before operator
src/lxml/etree.pyx:273:89:  E501 line too long (94 > 88 characters)
src/lxml/etree.pyx:275:89:  E501 line too long (99 > 88 characters)
src/lxml/etree.pyx:291:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:354:30:  E201 whitespace after '['
src/lxml/etree.pyx:354:73:  E202 whitespace before ']'
src/lxml/etree.pyx:391:16:  E221 multiple spaces before operator
src/lxml/etree.pyx:462:21: 'c_doc_ns' defined but unused
src/lxml/etree.pyx:467:17:  E122 continuation line missing indentation or outdented
src/lxml/etree.pyx:507:19:  E201 whitespace after '['
src/lxml/etree.pyx:508:38:  E202 whitespace before ']'
src/lxml/etree.pyx:531:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:536:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:582:37:  W602 deprecated form of raising exception
src/lxml/etree.pyx:582:89:  E501 line too long (94 > 88 characters)
src/lxml/etree.pyx:614:89:  E501 line too long (93 > 88 characters)
src/lxml/etree.pyx:656:9:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:681:89:  E501 line too long (89 > 88 characters)
src/lxml/etree.pyx:703:29:  E201 whitespace after '['
src/lxml/etree.pyx:703:70:  E202 whitespace before ']'
src/lxml/etree.pyx:725:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:726:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:746:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:763:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:800:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:813:61:  E261 at least two spaces before inline comment
src/lxml/etree.pyx:860:36:  W602 deprecated form of raising exception
src/lxml/etree.pyx:860:89:  E501 line too long (117 > 88 characters)
src/lxml/etree.pyx:879:36:  W602 deprecated form of raising exception
src/lxml/etree.pyx:879:89:  E501 line too long (117 > 88 characters)
src/lxml/etree.pyx:892:32:  W602 deprecated form of raising exception
src/lxml/etree.pyx:905:23: 'c_attr_next' defined but unused
src/lxml/etree.pyx:961:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:984:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1045:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:1062:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:1179:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1191:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:1234:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1256:20:  E127 continuation line over-indented for visual indent
src/lxml/etree.pyx:1257:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1267:13:  E741 ambiguous variable name 'l'
src/lxml/etree.pyx:1270:21:  E741 ambiguous variable name 'l'
src/lxml/etree.pyx:1274:35:  E741 ambiguous variable name 'l'
src/lxml/etree.pyx:1275:37:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1277:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1302:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1304:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1360:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:1372:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:1384:9:  E265 block comment should start with '# '
src/lxml/etree.pyx:1593:89:  E501 line too long (98 > 88 characters)
src/lxml/etree.pyx:1650:24:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1678:32: 'c_dict' defined but unused
src/lxml/etree.pyx:1693:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1769:17:  E201 whitespace after '{'
src/lxml/etree.pyx:1770:83:  E202 whitespace before '}'
src/lxml/etree.pyx:1772:49:  W605 invalid escape sequence '\s'
src/lxml/etree.pyx:1772:53:  W605 invalid escape sequence '\w'
src/lxml/etree.pyx:1772:57:  W605 invalid escape sequence '\s'
src/lxml/etree.pyx:1772:61:  W605 invalid escape sequence '\s'
src/lxml/etree.pyx:1772:89:  E501 line too long (105 > 88 characters)
src/lxml/etree.pyx:1789:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1827:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:1835:37:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1835:89:  E501 line too long (99 > 88 characters)
src/lxml/etree.pyx:1841:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1841:89:  E501 line too long (95 > 88 characters)
src/lxml/etree.pyx:1847:33:  E261 at least two spaces before inline comment
src/lxml/etree.pyx:1857:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:1859:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:1861:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:1872:33:  E201 whitespace after '['
src/lxml/etree.pyx:1873:56:  E202 whitespace before ']'
src/lxml/etree.pyx:1915:28:  W602 deprecated form of raising exception
src/lxml/etree.pyx:1963:16:  E127 continuation line over-indented for visual indent
src/lxml/etree.pyx:2102:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2106:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2133:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2139:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2142:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2175:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2293:89:  E501 line too long (98 > 88 characters)
src/lxml/etree.pyx:2440:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:2462:28:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2467:31:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2483:26:  E201 whitespace after '('
src/lxml/etree.pyx:2483:71:  E202 whitespace before ')'
src/lxml/etree.pyx:2497:27:  W602 deprecated form of raising exception
src/lxml/etree.pyx:2583:25:  E261 at least two spaces before inline comment
src/lxml/etree.pyx:2584:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:2618:39:  E201 whitespace after '['
src/lxml/etree.pyx:2619:70:  E202 whitespace before ']'
src/lxml/etree.pyx:2650:5:  E125 continuation line with same indent as next logical line
src/lxml/etree.pyx:2650:61:  E202 whitespace before ']'
src/lxml/etree.pyx:2657:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:2664:19:  E127 continuation line over-indented for visual indent
src/lxml/etree.pyx:2665:19:  E127 continuation line over-indented for visual indent
src/lxml/etree.pyx:2666:89:  E501 line too long (100 > 88 characters)
src/lxml/etree.pyx:2675:23: 'c_node' defined but unused
src/lxml/etree.pyx:2684:1:  E302 expected 2 blank lines, found 1
src/lxml/etree.pyx:2771:89:  E501 line too long (89 > 88 characters)
src/lxml/etree.pyx:2785:89:  E501 line too long (93 > 88 characters)
src/lxml/etree.pyx:2924:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:2926:23:  E221 multiple spaces before operator
src/lxml/etree.pyx:2987:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:3032:1:  E302 expected 2 blank lines, found 1
src/lxml/etree.pyx:3053:18:  E222 multiple spaces after operator
src/lxml/etree.pyx:3054:17:  E222 multiple spaces after operator
src/lxml/etree.pyx:3077:18:  E222 multiple spaces after operator
src/lxml/etree.pyx:3078:17:  E222 multiple spaces after operator
src/lxml/etree.pyx:3083:25:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3090:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3098:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/etree.pyx:3116:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:3119:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3133:18:  E222 multiple spaces after operator
src/lxml/etree.pyx:3134:17:  E222 multiple spaces after operator
src/lxml/etree.pyx:3139:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3141:25:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3164:19: 'c_next' defined but unused
src/lxml/etree.pyx:3165:19: 'c_node' defined but unused
src/lxml/etree.pyx:3166:19: 'c_node_copy' defined but unused
src/lxml/etree.pyx:3167:17:  E222 multiple spaces after operator
src/lxml/etree.pyx:3168:23: 'etree' defined but unused
src/lxml/etree.pyx:3172:12:  E221 multiple spaces before operator
src/lxml/etree.pyx:3272:20: 'doc' defined but unused
src/lxml/etree.pyx:3318:89:  E501 line too long (107 > 88 characters)
src/lxml/etree.pyx:3421:89:  E501 line too long (98 > 88 characters)
src/lxml/etree.pyx:3435:29:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3465:24:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3465:89:  E501 line too long (109 > 88 characters)
src/lxml/etree.pyx:3469:1:  E303 too many blank lines (3)
src/lxml/etree.pyx:3506:27:  E127 continuation line over-indented for visual indent
src/lxml/etree.pyx:3512:24:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3588:27:  E261 at least two spaces before inline comment
src/lxml/etree.pyx:3594:27:  E261 at least two spaces before inline comment
src/lxml/etree.pyx:3625:5:  E301 expected 1 blank line, found 0
src/lxml/etree.pyx:3653:33:  W602 deprecated form of raising exception
src/lxml/etree.pyx:3673:25:  E261 at least two spaces before inline comment
src/lxml/objectify.pyx:14:89:  E501 line too long (91 > 88 characters)
src/lxml/objectify.pyx:15:89:  E501 line too long (92 > 88 characters)
src/lxml/objectify.pyx:85:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:110:22:  E221 multiple spaces before operator
src/lxml/objectify.pyx:112:5: 'PYTYPE_ATTRIBUTE' defined but unused
src/lxml/objectify.pyx:115:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:245:28:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:245:89:  E501 line too long (96 > 88 characters)
src/lxml/objectify.pyx:302:29:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:310:29:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:339:28:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:353:33:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:360:28:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:382:89:  E501 line too long (97 > 88 characters)
src/lxml/objectify.pyx:396:10:  E221 multiple spaces before operator
src/lxml/objectify.pyx:439:20:  E261 at least two spaces before inline comment
src/lxml/objectify.pyx:453:29:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:524:29: 'c_start' defined but unused
src/lxml/objectify.pyx:531:25:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:551:25:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:552:89:  E501 line too long (109 > 88 characters)
src/lxml/objectify.pyx:727:20:  E201 whitespace after '('
src/lxml/objectify.pyx:727:42:  E202 whitespace before ')'
src/lxml/objectify.pyx:818:13:  E221 multiple spaces before operator
src/lxml/objectify.pyx:823:13:  E221 multiple spaces before operator
src/lxml/objectify.pyx:829:89:  E501 line too long (89 > 88 characters)
src/lxml/objectify.pyx:831:89:  E501 line too long (89 > 88 characters)
src/lxml/objectify.pyx:929:25:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1016:89:  E501 line too long (101 > 88 characters)
src/lxml/objectify.pyx:1033:89:  E501 line too long (99 > 88 characters)
src/lxml/objectify.pyx:1036:89:  E501 line too long (108 > 88 characters)
src/lxml/objectify.pyx:1046:89:  E501 line too long (110 > 88 characters)
src/lxml/objectify.pyx:1086:9:  E221 multiple spaces before operator
src/lxml/objectify.pyx:1119:5:  E301 expected 1 blank line, found 0
src/lxml/objectify.pyx:1123:28:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1125:28:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1127:16:  E127 continuation line over-indented for visual indent
src/lxml/objectify.pyx:1128:28:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1130:18:  E221 multiple spaces before operator
src/lxml/objectify.pyx:1152:29:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1174:33:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1192:33:  E201 whitespace after '('
src/lxml/objectify.pyx:1192:57:  E202 whitespace before ')'
src/lxml/objectify.pyx:1203:9:  E301 expected 1 blank line, found 0
src/lxml/objectify.pyx:1226:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1233:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1245:89:  E501 line too long (98 > 88 characters)
src/lxml/objectify.pyx:1249:89:  E501 line too long (94 > 88 characters)
src/lxml/objectify.pyx:1272:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1301:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1319:1:  W293 blank line contains whitespace
src/lxml/objectify.pyx:1331:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1432:89:  E501 line too long (107 > 88 characters)
src/lxml/objectify.pyx:1436:89:  E501 line too long (95 > 88 characters)
src/lxml/objectify.pyx:1454:5:  E301 expected 1 blank line, found 0
src/lxml/objectify.pyx:1464:89:  E501 line too long (101 > 88 characters)
src/lxml/objectify.pyx:1473:89:  E501 line too long (90 > 88 characters)
src/lxml/objectify.pyx:1505:30:  E261 at least two spaces before inline comment
src/lxml/objectify.pyx:1507:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1514:5: '__RECURSIVE_STR' defined but unused
src/lxml/objectify.pyx:1516:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1523:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1535:11:  E221 multiple spaces before operator
src/lxml/objectify.pyx:1551:27:  E261 at least two spaces before inline comment
src/lxml/objectify.pyx:1562:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1570:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1573:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1585:5:  E301 expected 1 blank line, found 0
src/lxml/objectify.pyx:1611:9:  E125 continuation line with same indent as next logical line
src/lxml/objectify.pyx:1664:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1665:14:  E128 continuation line under-indented for visual indent
src/lxml/objectify.pyx:1666:89:  E501 line too long (90 > 88 characters)
src/lxml/objectify.pyx:1687:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1689:89:  E501 line too long (92 > 88 characters)
src/lxml/objectify.pyx:1715:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1718:89:  E501 line too long (139 > 88 characters)
src/lxml/objectify.pyx:1730:25:  W291 trailing whitespace
src/lxml/objectify.pyx:1731:1:  W293 blank line contains whitespace
src/lxml/objectify.pyx:1746:61:  W291 trailing whitespace
src/lxml/objectify.pyx:1775:12:  E221 multiple spaces before operator
src/lxml/objectify.pyx:1792:21:  E222 multiple spaces after operator
src/lxml/objectify.pyx:1799:9:  E125 continuation line with same indent as next logical line
src/lxml/objectify.pyx:1887:89:  E501 line too long (90 > 88 characters)
src/lxml/objectify.pyx:1904:89:  E501 line too long (94 > 88 characters)
src/lxml/objectify.pyx:1911:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1913:89:  E501 line too long (99 > 88 characters)
src/lxml/objectify.pyx:1919:75:  W291 trailing whitespace
src/lxml/objectify.pyx:1944:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1946:43:  E201 whitespace after '('
src/lxml/objectify.pyx:1946:73:  E202 whitespace before ')'
src/lxml/objectify.pyx:1951:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1951:34:  E251 unexpected spaces around keyword / parameter equals
src/lxml/objectify.pyx:1951:36:  E251 unexpected spaces around keyword / parameter equals
src/lxml/objectify.pyx:1967:24:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:1969:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:1982:37:  E201 whitespace after '('
src/lxml/objectify.pyx:1982:67:  E202 whitespace before ')'
src/lxml/objectify.pyx:1985:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:1996:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:2012:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:2028:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:2031:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:2046:1:  E305 expected 2 blank lines after class or function definition, found 1
src/lxml/objectify.pyx:2054:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:2074:1:  E302 expected 2 blank lines, found 1
src/lxml/objectify.pyx:2076:89:  E501 line too long (92 > 88 characters)
src/lxml/objectify.pyx:2125:33:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:2137:33:  W602 deprecated form of raising exception
src/lxml/objectify.pyx:2165:28:  W291 trailing whitespace
```

**Comment by scoder** [comment]
Thanks. I hadn't heard about that tool before. Very nice.

It looks like it doesn't take into account Cython's `import` command, though. It does not report any issues in the `.pxi` files, and it also seems to report "unused" names that are probably in use, but only in those included files.

Also, I'm fine with 120 characters in a source line, so the "line to long" errors are unhelpful.

Overall, I'm not sure that I want to include the tool just yet. But thanks for bringing this up and listing the results here. There are certainly a few things that can be cleaned up.

**Comment by cclauss** [comment]
Perhaps the `--no-pycodestyle` is more of interest.  Adding the `.pyi` files seem to have no effect on `imported but unused`

% `cython-lint --max-line-length=120 --no-pycodestyle **/*.pyi **/*.pyx`
```
src/lxml/etree.pyx:50:34: 'config' imported but unused
src/lxml/etree.pyx:54:28: 'xpath' imported but unused
src/lxml/etree.pyx:55:28: 'c14n' imported but unused
src/lxml/etree.pyx:60:19: 'limits' imported but unused
src/lxml/etree.pyx:60:34: 'stdlib' imported but unused
src/lxml/etree.pyx:61:19: 'cstring_h' imported but unused
src/lxml/etree.pyx:62:26: 'const_char' imported but unused
src/lxml/etree.pyx:65:21: 'os_path_abspath' imported but unused
src/lxml/etree.pyx:68:25: 'StringIO' imported but unused
src/lxml/etree.pyx:71:25: 'OrderedDict' imported but unused
src/lxml/etree.pyx:83:23: 'partial' imported but unused
src/lxml/etree.pyx:86:23: 'islice' imported but unused
src/lxml/etree.pyx:181:5: '_DEFAULT_NAMESPACE_PREFIXES_ITEMS' defined but unused
src/lxml/etree.pyx:462:21: 'c_doc_ns' defined but unused
src/lxml/etree.pyx:905:23: 'c_attr_next' defined but unused
src/lxml/etree.pyx:1678:32: 'c_dict' defined but unused
src/lxml/etree.pyx:2675:23: 'c_node' defined but unused
src/lxml/etree.pyx:3164:19: 'c_next' defined but unused
src/lxml/etree.pyx:3165:19: 'c_node' defined but unused
src/lxml/etree.pyx:3166:19: 'c_node_copy' defined but unused
src/lxml/etree.pyx:3168:23: 'etree' defined but unused
src/lxml/etree.pyx:3272:20: 'doc' defined but unused
src/lxml/objectify.pyx:112:5: 'PYTYPE_ATTRIBUTE' defined but unused
src/lxml/objectify.pyx:524:29: 'c_start' defined but unused
src/lxml/objectify.pyx:1514:5: '__RECURSIVE_STR' defined but unused
```

**Comment by scoder** [comment]
I really meant `.pxi`, as I wrote, not `.pyi`.

**Comment by cclauss** [comment]
That shows how much I know about Cython

**Pull request closed without merging**
