### PR TITLE
fix html.SelectElement stripping whitespace from <option> values

### PR DESCRIPTION
**Pull request by ashkulz**
This is a fix for [bug #1665241](https://bugs.launchpad.net/lxml/+bug/1665241). I've tried to add tests, please let me know if any changes need to be made.

### CODE REVIEW

**Comment by scoder** [comment]
Nice, thanks!

**Comment by ashkulz** [comment]
Should I submit a PR for backporting it to the `3.7` branch? A `3.7.2` release is likely to get into the upcoming Debian release (either `stretch` or `stretch-backports`) :smile:

Also, Travis CI doesn't seem to be working although it seems to be configured -- is it disabled for some reason?

**Comment by scoder** [comment]
While a bug-fix, this is also a change of long-standing behaviour that does not strictly belong into a 3.7.3.

**Comment by ashkulz** [comment]
Fair enough. I've submitted a PR to scrapy to document this, as I encountered it while using it.

**Pull request merged**
