### PR TITLE
add compiling for armv7l

### PR DESCRIPTION
**Pull request by pietrocolombo**
I would like to add the compiling also for armv7l

### CODE REVIEW

**Comment by scoder** [comment]
Is the intention to support the Raspberry Pi, or what is the goal here?

**Comment by pietrocolombo** [comment]
I am doing a project with this device:BeagleBone® Blackbeagleboard.orgThe operating system is debian, but since I have limited ram I have problems compiling.Best,PietroIl giorno 9 ott 2024, alle ore 06:20, scoder ***@***.***> ha scritto:﻿
Is the intention to support the Raspberry Pi, or what is the goal here?

**Comment by scoder** [comment]
This doesn't look successful:
https://github.com/lxml/lxml/actions/runs/11230911550/job/31272830044

We use `cibuildwheel` for the wheel build, which prints:
`ValueError: 'armv7l' is not a valid Architecture`

**Comment by pietrocolombo** [comment]
[https://github.com/pypa/cibuildwheel/issues/1421](https://github.com/pypa/cibuildwheel/issues/1421
)

They added support with the v2.21.2 version of cibuildwheel

**Comment by scoder** [comment]
In it is. I've removed a few older Python versions from the build matrix in order to make up for the increased build times. Emulated platforms take >100 minutes to build, eating a lot of energy along the way.

**Pull request merged**
