### PR TITLE
appveyor: fix use of the selected Python version

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by anthrotype** [comment]
isn't line 17 (`SET PATH ...`) supposed to make sure that the selected python version is in the `%PATH%`?
Maybe the `%PYTHON%` enviornment variable isn't defined.

**Comment by mr-c** [comment]
@anthrotype That is what I thought. This PR syncs with a known working configuration https://github.com/common-workflow-language/schema_salad/blob/master/appveyor.yml

**Comment by mr-c** [comment]
> Now that you have defined `PYTHON` in the environment matrix and set `PATH` accordingly,

Well, now we do `set PATH=%PYTHON%\\Scripts;%PATH%` instead of `SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%` so the full path is needed to `python.exe`

I agree about 
> `python -m pip` works (`pip.__main__` is unnecessary)

**Comment by anthrotype** [comment]
> Well, now we do set PATH=%PYTHON%\\Scripts;%PATH% instead of

I see. But I not simply keeping `%PYTHON%` directory itself in the PATH and calling python as `python` as one would normally do?

**Comment by mr-c** [comment]
@anthrotype I was sticking to a known good recipe. I am happy to make your change, if the `lxml` maintainers wish for it

**Comment by scoder** [comment]
Superseded by the current build setup.

**Pull request closed without merging**
